language: node_js
node_js:
  - v12
  - v10
  - v8
  - v6
after_script: cat ./coverage/lcov.info | coveralls
before_script:
  - node --version
  - npm --version
before_install:
  - npm i -g npm@latest
